### ISSUE TITLE
MVP Requirement Plan

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#2]
It seems we came to a conclusion via chat.makerdao.com :

Oasis.Direct MVP Requirement Plan :

Using Scenario I
Iframe widget with simple integration possibility
Only native ETH to ERC-20 exchange at the beginning
Only one transaction required

**Comment by pimato** [comment]
icon package:
[od-icons.zip](https://github.com/OasisDEX/oasis-direct/files/1358772/od-icons.zip)

asset colors:
ether: #4F6CB1
maker: #3AB493
augur: #963C81
golem: #1565C0
digix: #EF6C00
sai: #F7A600

**Comment by peculiarity** [comment]
The file with the dimensions doesn't include the tokens list part.

**Comment by pimato** [comment]
no changes will be made to the picker, until the mvp is implemented:

![picker](https://user-images.githubusercontent.com/5337809/31231099-2897ccb8-a9e6-11e7-86aa-8f167b40b7ee.png)

**Comment by pimato** [comment]
required design work:

- [ ] display a message if the user wants to use an Amount which is greater then his current balance.
- [ ] display --> Metamask not available 
- [ ] display --> Metamask is locked

**Comment by pimato** [comment]
**Task :** display a message if the user wants to use an Amount which is greater then his current balance.

<img width="664" alt="bildschirmfoto 2017-10-14 um 15 58 13" src="https://user-images.githubusercontent.com/5337809/31576316-87d0c93c-b0f8-11e7-8102-8af543f5badb.png">

Specs: https://drive.google.com/file/d/0By-T9wgbMXfJVGVhWFBmSXRkUFk/view?usp=sharing

**Comment by pimato** [comment]
**Task** : display --> Metamask is locked

<img width="687" alt="bildschirmfoto 2017-10-16 um 17 17 47" src="https://user-images.githubusercontent.com/5337809/31619828-f554cc9e-b295-11e7-8fac-1096827aa91c.png">

**Logo**: [icn_metamask.svg.zip](https://github.com/OasisDEX/oasis-direct/files/1387982/icn_metamask.svg.zip)

**Specs:** [od-metamask.zip](https://github.com/OasisDEX/oasis-direct/files/1387993/od-metamask.zip)

**Comment by pimato** [comment]
**Task**: display --> Metamask not available

<img width="746" alt="bildschirmfoto 2017-10-17 um 14 34 36" src="https://user-images.githubusercontent.com/5337809/31665236-6d9d56dc-b348-11e7-91f8-8143cd9cad99.png">

**Logos**: [Archiv.zip](https://github.com/OasisDEX/oasis-direct/files/1390998/Archiv.zip)
**Specs**: [no-ethereum.zip](https://github.com/OasisDEX/oasis-direct/files/1391004/no-ethereum.zip)

**Comment by pimato** [comment]
Update:

**optimal buy:**
![oasis-direct-optimal](https://user-images.githubusercontent.com/5337809/31862917-9817dd5e-b746-11e7-889f-4de42905cf6b.png)

**finalize trade:**
![oasis-direct-finalize-trade](https://user-images.githubusercontent.com/5337809/31863144-8f26d7ba-b749-11e7-8192-4ca24b99e8af.png)

**Comment by peculiarity** [comment]
1. I don't see ( or at least for now ) any benefit in having this `...current estimated price...` in the finalize trade.

2. The Finalize trade view itself is two much compicated in my opinion. What do I have those token boxes which looks like buttons ( from first view - token selector ) . What 's the added value from those two and why not leave the transaction 1/2 panels only ?

**Comment by gbalabasquer** [comment]
Quick feedback, I'll take a closer look later. We should need another "Finalize Trade" version when we sell native eth, it should use just one step.
We still also need to research a bit the case we need to create the proxy in that moment. For the case of native eth, we can still do everything in one tx, for the case of selling tokens, we might need even 3 txs, but need to think about it.

**Comment by pimato** [comment]
@gbalabasquer @peculiarity I updated the "finalize trade" view : 

**scenario I (user is buying ERC-20 token with native ETH):** 

![oasis-direct-transaction-one](https://user-images.githubusercontent.com/5337809/31866134-ecacffa0-b77a-11e7-820e-4f115a15f75a.png)

**scenario II (user is buying ETH/ERC-20 token with ERC-20 token):** 

![oasis-direct-transaction-two](https://user-images.githubusercontent.com/5337809/31866150-236fdfd0-b77b-11e7-8ab8-d05d83045c8d.png)

**scenario III (user is buying ETH/ERC-20 token with ERC-20 token without an Account):** 

![oasis-direct-transaction-three](https://user-images.githubusercontent.com/5337809/31866158-4774792c-b77b-11e7-94ce-d65b94352edc.png)

**Comment by deepinit-arek** [comment]
I really like new version much more. It is actually much more informative and keeps user involved and informed.
There is continuous feedback loop, which is really important.
In my opinion its really big improvement over the previous version.

**Comment by pimato** [comment]
Requirement Update:
Token-Pairs which should be enbabled:
-  `ETH/DAI`, `ETH/MKR`
- `MKR/ETH`, `MKR/DAI`
-  `DAI/ETH`, `DAI/MKR`

**Comment by pimato** [comment]
I have changed a few things after seeing the mockups live on www.oasis-direct.surge.sh:

- increasing the dimensions of the widget from `364x324` to `420x380`
- I updated the mockups to represent the new binary allowance approach.

With the support contract, we can reduce the amount of transactions to max. 2 transactions. With that I have updated the current mockups to represent two versions of "finalizing trade. 

### Finalize trade with one transaction

![finalize-trade-one](https://user-images.githubusercontent.com/5337809/34917212-a1e588b0-f943-11e7-8f0c-46aa10b4eb77.png)

### Finalize trade with two transaction

![finalize-trade-two](https://user-images.githubusercontent.com/5337809/34917213-ac68b398-f943-11e7-8671-7a15d4b6295e.png)
